# Generated by Django 2.2.3 on 2019-08-06 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photogur', '0003_picture_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='picture',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='picture',
            name='url',
            field=models.CharField(max_length=255, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
